### ISSUE TITLE
KeyError: "The name 'input_image:0' refers to a Tensor which does not exist. The operation, 'input_image', does not exist in the graph."?

### ISSUE THREAD

**Issue by ibrahimLearning** [bendangnuksung/mrcnn_serving_ready#14]
However I run your code in CPU mode. but it gives the following error:

> KeyError: "The name 'input_image:0' refers to a Tensor which does not exist. The operation, 'input_image', does not exist in the graph."

Would you help me please?

Thanks

**Comment by bendangnuksung** [comment]
The tensor `input_image` should be in the Graph, are you loading the right model? and have you tried loading the same config class which you used for training?

**Comment by i-chaochen** [comment]
Hi, thanks for sharing this serving_ready

I can create and load the frozen graph now. 

After I loaded the graph, I can get_tensor_by_name('input_image:0'), but what about the outputs?

I tried the following, and none of is worked.
```
tf_rois = tf_sess.graph.get_tensor_by_name('rois:0') 
tf_masks = tf_sess.graph.get_tensor_by_name('mask:0') 
tf_class_ids = tf_sess.graph.get_tensor_by_name('class_ids:0') 
tf_scores = tf_sess.graph.get_tensor_by_name('scores:0') 
```

**Comment by ibrahimLearning** [comment]
@bendangnuksung @i-chaochen 
problem is solved. The tensor name was not same as .pb file. thanks

**Comment by i-chaochen** [comment]
> problem is solved. The tensor name was not same as .pb file. thanks

so where do you know the tensor name from the frozen graph?

**Comment by ibrahimLearning** [comment]
During creating the freeze_graph, just print model.inputs and model.outputs. In my case, the name was
input_image_7.  Thanks

**Comment by Asher94** [comment]
How did you get the output for the model.inputs? I tried printing them but nothing appeared.
