### ISSUE TITLE
Frozen graph generates difference results compared to the original model

### ISSUE THREAD

**Issue by i-chaochen** [bendangnuksung/mrcnn_serving_ready#16]
After I generated the frozen graph, and I loaded it to run the inference with a picture, the detection result is different than I directly run the model

For example, I run directly from the model I can have detentions as the following. 
```
	detections[:,4] [1. 1. 1. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0.]
```

But when I run my frozen graph I will have the following results
```
	detections[:,4] [1. 1. 1. 3. **3. 9.** 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	 0. 0. 0. 0.]
```

I checked the first 4 detentions are similar, but the frozen graph has 2 different ones, any ideas why frozen graph will generate different detection results, and how to solve it?

Thanks

**Comment by VaneeshK** [comment]
@i-chaochen @bendangnuksung Hi,
I am facing the same problem the converted model predictions are different as compare to original model.
For some images there is very minute difference but if I send the image with no classes it still detecting the classes with very high confidence. the original model is working as expected.

Can anyone help why after conversion there is a difference between the predictions?

**Comment by i-chaochen** [comment]
> @i-chaochen @bendangnuksung Hi,
> I am facing the same problem the converted model predictions are different as compare to original model.
> For some images there is very minute difference but if I send the image with no classes it still detecting the classes with very high confidence. the original model is working as expected.
> 
> Can anyone help why after conversion there is a difference between the predictions?

Sorry mate, I cannot remember exactly how did I solve this issue before...

You can google "frozen tensorflow model different results", there are many reasons behind it.
