### ISSUE TITLE
there is not any files in the folder about serving_model/1/variables.

### ISSUE THREAD

**Issue by LymanLiuChina** [bendangnuksung/mrcnn_serving_ready#17]
hello, I executed main.py, but I didn't find any files in /serving_model/1/variables. 
Is it correct？

**Comment by bendangnuksung** [comment]
Have you modified the Path variables in `user_config.py` ?

**Comment by LymanLiuChina** [comment]
I just modified a little, because I just need serving_model about mask_rcnn_coco.h5. but, in the /serving_model/1/, there is saved_model.pd,but in the /serving_model/1/variables, there isn't any file.
this is my directory,
![image](https://user-images.githubusercontent.com/32006524/62223035-db068b80-b3e6-11e9-9c07-0ef0627620b6.png)


this is my user_config.py:

![image](https://user-images.githubusercontent.com/32006524/62223356-5ec07800-b3e7-11e9-8734-933cbcfa1768.png)

**Comment by bendangnuksung** [comment]
Can you show me the full error that you are getting.

**Comment by huyhoang17** [comment]
@LymanLiuChina there is no need any files in `variables` folder. I used tensorflow serving and it's serve my .pb model successfully.

**Comment by deepakks1995** [comment]
@LymanLiuChina  I faced the same issue, it's because the whole model is frozen at the time of exporting it. So variables folder only contain graph meta data, weights which can be used to restore the graph for training. Since we don't require any training at inference hence we have totally frozen the graph, that's why if you open the saved_model.pb file you will find the network architecture along with the frozen constants of the network. If we don't froze the graph these constants will not appear in the protoBuff file and would be saved in weights file inside variables folder.

**Comment by LymanLiuChina** [comment]
> @LymanLiuChina there is no need any files in `variables` folder. I used tensorflow serving and it's serve my .pb model successfully.

I got it, thank you!

**Comment by LymanLiuChina** [comment]
> @LymanLiuChina I faced the same issue, it's because the whole model is frozen at the time of exporting it. So variables folder only contain graph meta data, weights which can be used to restore the graph for training. Since we don't require any training at inference hence we have totally frozen the graph, that's why if you open the saved_model.pb file you will find the network architecture along with the frozen constants of the network. If we don't froze the graph these constants will not appear in the protoBuff file and would be saved in weights file inside variables folder.



> @LymanLiuChina I faced the same issue, it's because the whole model is frozen at the time of exporting it. So variables folder only contain graph meta data, weights which can be used to restore the graph for training. Since we don't require any training at inference hence we have totally frozen the graph, that's why if you open the saved_model.pb file you will find the network architecture along with the frozen constants of the network. If we don't froze the graph these constants will not appear in the protoBuff file and would be saved in weights file inside variables folder.

h

> 你能告诉我你得到的完整错误吗？

thank you, @huyhoang17 has told me why this problem arises.

**Comment by LymanLiuChina** [comment]
> @LymanLiuChina there is no need any files in `variables` folder. I used tensorflow serving and it's serve my .pb model successfully.

I am a novice, I want to deploy the mask model on the server, but according to many online tutorials, I still have many problems. Can you give me a complete Python source code (server and client) for your deployment of the maskrcnmo model?

**Comment by LymanLiuChina** [comment]
you

> @LymanLiuChina there is no need any files in `variables` folder. I used tensorflow serving and it's serve my .pb model successfully.

I am a novice, I want to deploy the mask model on the server, but according to many online tutorials, I still have many problems. Could you give me a complete Python source code (server and client) for your deployment of the maskrcnmo model?
Thank you!
this my email: 269779795@qq.com

**Comment by LymanLiuChina** [comment]
> @LymanLiuChina there is no need any files in `variables` folder. I used tensorflow serving and it's serve my .pb model successfully.

I am a novice, I want to deploy the mask model on the server, but according to many online tutorials, I still have many problems. Could you give me a complete Python source code (server and client) for your deployment of the maskrcnmo model?
Thank you!
this my email: 269779795@qq.com

**Comment by LymanLiuChina** [comment]
> @LymanLiuChina I faced the same issue, it's because the whole model is frozen at the time of exporting it. So variables folder only contain graph meta data, weights which can be used to restore the graph for training. Since we don't require any training at inference hence we have totally frozen the graph, that's why if you open the saved_model.pb file you will find the network architecture along with the frozen constants of the network. If we don't froze the graph these constants will not appear in the protoBuff file and would be saved in weights file inside variables folder.

Thank you. I understand!
Have you used this service_model successfully?
How do you call this model on the client?
Could you share a source code with me?

**Comment by huyhoang17** [comment]
@LymanLiuChina hi, you can refer my serving code using gRPC on my github's repo: https://github.com/huyhoang17/matterport-maskrcnn-with-tensorflow-serving/blob/master/serve.py

Hope this answer helps you :smile: 
Any contributors are welcome :star: :100:

**Comment by huyhoang17** [comment]
and thank you @bendangnuksung for your awesome project :+1: :100: it's help me so much, thank you!

**Comment by bendangnuksung** [comment]
Closing as the original issue has been resolved.
