### ISSUE TITLE
Which .pb file should I use? The one in serving model or the one in frozen model?

### ISSUE THREAD

**Issue by boycao** [bendangnuksung/mrcnn_serving_ready#18]
Hi there,

There are two different .pb file in both tensorflow_serving_model and the frozen_pb. If I want to inference the model, which .pb file should I use? Thanks.

**Comment by bendangnuksung** [comment]
If you are inferencing using Tensorflow Model Server go for `saved_model.pb` otherwise you can `frozen_model.pb` for normal Tensorflow inference

**Comment by boycao** [comment]
Thanks!
