### ISSUE TITLE
How to use saved_model.pb in Tensorflow Model Server？

### ISSUE THREAD

**Issue by LymanLiuChina** [bendangnuksung/mrcnn_serving_ready#19]
hello,this saved_model.pd has been loaded into tensorflow_model server, but I do not know how to inference in client,  could you help me ? thanks!

**Comment by kbrajwani** [comment]
hey have you find the way to do it? i have same question.

**Comment by LymanLiuChina** [comment]
> hey have you find the way to do it? i have same question.
I still haven't solved this problem. Have you solved it?

**Comment by cpoptic** [comment]
Nope

**Comment by huyhoang17** [comment]
@LymanLiuChina you can refer to my repo: https://github.com/huyhoang17/matterport-maskrcnn-with-tensorflow-serving

**Comment by LymanLiuChina** [comment]
> @LymanLiuChina你可以参考我的仓库：[https](https://github.com/huyhoang17/matterport-maskrcnn-with-tensorflow-serving) : [//github.com/huyhoang17/matterport-maskrcnn-with-tensorflow-serving](https://github.com/huyhoang17/matterport-maskrcnn-with-tensorflow-serving)

Thank you. I've read this article, but it seems that it lacks some documents。

**Comment by LymanLiuChina** [comment]
> @LymanLiuChina you can refer to my repo: https://github.com/huyhoang17/matterport-maskrcnn-with-tensorflow-serving

could you give me your complete code? Cuz，I don't understand some code, for example, import uuid ,  from api.helpers import utils as api_utils ...
thank you!

**Comment by bendangnuksung** [comment]
Hi! just update the code for inferencing using TensorFlow serving. Please check ReadMe. 
**Note:** It uses GRPC not RESTAPI

**Comment by LymanLiuChina** [comment]
> It uses GRPC



> **te:** It uses GRPC not RE

thanks , i got it ,hahaha....., I succeed
