### ISSUE TITLE
Inference speed really slow!

### ISSUE THREAD

**Issue by MeghaGhosh** [bendangnuksung/mrcnn_serving_ready#26]
Hey, I converted the h5 model into pb with the given instructions, hoping that the inference speed would improve. It does take less time(~6s) for inference compared to h5(~13s) on CPU. Both are taking around 30s for the first inference and then speeds up to the time mentioned above. However, there is no improvement in speed on GPU, and sometimes it is even slower than CPU. How can I serve my model with the lowest inference speed possible? What speed is expected from the inference for mask RCNN in general?

**Comment by bendangnuksung** [comment]
Are you using TF serving GPU docker for inferencing? Coz the default `apt-get install tensorflow-model-server` does not uses the GPU.

**Comment by bendangnuksung** [comment]
Closing due to inactive. Open anytime if you want to come back on it.
