### ISSUE TITLE
how can I use the pb file to inference

### ISSUE THREAD

**Issue by wlsonia** [bendangnuksung/mrcnn_serving_ready#5]
Dear bendangnuksung,

First of all thanks for the code it was really helpful.
but,I have a question,how can I use the pb file to inference?

**Comment by bendangnuksung** [comment]
Hi! I was able to do the inference file using [this](https://github.com/matterport/Mask_RCNN/issues/218#issuecomment-476106031).  </br>
There is a typo. Do change it from:
```
forward_model = Forward('path/to/pb/', my_config)
results = forward_model(list_of_image_arrays)
```
to:
```
forward_model = ForwardModel('path/to/pb/', my_config)
results = forward_model(list_of_image_arrays)
```

**Comment by buaacarzp** [comment]
what's the list_of_image_arrays?

**Comment by rahulgullan** [comment]
Hi bendangnuksung,
Very thanks to your code. It helped me a lot
The client  code use gRPC to send the request. How can I implement the same using HTTP request. I'm really strugging to  create the 'request body'  with test image.
