### ISSUE TITLE
In the coco model, when I use resnet100 and resnet50 to generate h5 files to pb files respectively, why can both be generated ok?

### ISSUE THREAD

**Issue by buaacarzp** [bendangnuksung/mrcnn_serving_ready#8]
In the coco model, when I use resnet100 and resnet50 to generate h5 files to pb files respectively, why can both be used?

**Comment by bendangnuksung** [comment]
Hi, @buaacarzp Sorry but I am not being able to understand your issue clearly. 
[Mask_RCNN](https://github.com/matterport/Mask_RCNN) has used ResNet 101 as backbone. All I have done is to convert the Mask_RCNN  (which by default uses ResNet 101) Keras model to Tensorflow frozen and serving model. If that answers your question.

**Comment by buaacarzp** [comment]
hey, I am so happy to receive your response. when I set the" self.BACKBONE = "resnet101"" ,the .pb file was successfully created, and I set the " self.BACKBONE = "resnet50" ,the pb file was successfully created too. my question is that how can I test the pb model is right? can I use the pb file which I created to inference the model?
because I want to generate teh pb file and the pbtxt file to use the opencv  by c++ to run the maskrcnn. so,now I counld not to guess that my pb file is right, could you please help me ?
thank you.



18811746117@163.com
 
From: Bendang
Date: 2019-06-06 20:25
To: bendangnuksung/mrcnn_serving_ready
CC: buaacarzp; Mention
Subject: Re: [bendangnuksung/mrcnn_serving_ready] In the coco model, when I use resnet100 and resnet50 to generate h5 files to pb files respectively, why can both be generated ok? (#8)
Hi, @buaacarzp Sorry but I am not being able to understand your issue clearly.
Mask_RCNN has used ResNet 101 as backbone. All I have done is to convert the Mask_RCNN (which by default uses ResNet 101) Keras model to Tensorflow frozen and serving model. If that answers your question.

**Comment by bendangnuksung** [comment]
Glad to help. To test 'mask_frozen_graph.pb'  for inference please refer https://github.com/bendangnuksung/mrcnn_serving_ready/issues/5#issuecomment-485647139

**Comment by buaacarzp** [comment]
hey,now I have a trouble in there.
first of all,  what's the use of serving model?
the second ,why I meet a wrong  when I use the image to test the  file of "forward.py" to test the "mask_frozen_graph.pb'" ? here is my code to call the forward.py:
`from forward import ForwardModel
import cv2
import skimage
is_coco=True
def get_config1():
    if is_coco:
        import coco
        class InferenceConfig(coco.CocoConfig):
            GPU_COUNT = 1
            IMAGES_PER_GPU = 1

        config = InferenceConfig()

    else:
#        config = mask_config(NUMBER_OF_CLASSES)
        pass

    return config
my_config=get_config1()

forward_model = ForwardModel('./frozen_model/mask_frozen_graph.pb', my_config)
#forward_model = ForwardModel('./serving_model/1/saved_model.pb', my_config)
list_of_image_arrays=cv2.imread("./zp.jpg")
skimage.transform.rescale(list_of_image_arrays, (4,4))
#if list_of_image_arrays.ndim != 3:
#    list_of_image_arrays = skimage.color.gray2rgb(list_of_image_arrays)
#        # If has an alpha channel, remove it for consistency
#if list_of_image_arrays.shape[-1] == 4:
#    list_of_image_arrays = list_of_image_arrays[..., :3]


results = forward_model(list_of_image_arrays)`
but  it give me a wrong message:
`ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,2) and requested shape (2,2)
`
I am true that my image is RGB, why ...... I am so sad and confused.... please help me ,handsome boy.

**Comment by bendangnuksung** [comment]
1. Serving model can be used by `tensorflow_model_server` to deploy models on production.
2. `forward_model` expects a list of images. i.e it requires input shape of (N_Images, height, width, channel)

here is the code I use to call the `forward_model`
```python
from forward import ForwardModel
import cv2
import numpy as np

frozen_graph_path = "frozen_model/mask_frozen_graph.pb"

# assign your own Config class
from config import mask_config
my_config = mask_config(5)

forward_model = ForwardModel(frozen_graph_path, my_config)

def test_one_image(image):
    images = np.expand_dims(image, axis=0)
    results = forward_model(images)
    return results

if __name__ == "__main__":
    test_image_path = 'XYZ.jpg'
    image = cv2.imread(test_image_path)
    r = test_one_image(image)
    print(r)
```

**Comment by buaacarzp** [comment]
>     1. Serving model can be used by `tensorflow_model_server` to deploy models on production.
> 
>     2. `forward_model` expects a list of images. i.e it requires input shape of (N_Images, height, width, channel)
> 
> 
> here is the code I use to call the `forward_model`
> 
> ```python
> from forward import ForwardModel
> import cv2
> import numpy as np
> 
> frozen_graph_path = "frozen_model/mask_frozen_graph.pb"
> 
> # assign your own Config class
> from config import mask_config
> my_config = mask_config(5)
> 
> forward_model = ForwardModel(frozen_graph_path, my_config)
> 
> def test_one_image(image):
>     images = np.expand_dims(image, axis=0)
>     results = forward_model(images)
>     return results
> 
> if __name__ == "__main__":
>     test_image_path = 'XYZ.jpg'
>     image = cv2.imread(test_image_path)
>     r = test_one_image(image)
>     print(r)
> ```

I feel so touched that you reply me, you are a goodness boy, but when I use your code to test the coco.h5,  this model have 81 classes, so I change the 5 to 81, but it give me a wrong message:
```
ValueError: Cannot feed value of shape (1, 94) for Tensor 'import/input_image_meta:0', which has shape '(?, 93)'

```
How can I solve this problem? I feel it have a little distance to  the victory, please help me again. I want to make friends with you, it's my honer.

**Comment by buaacarzp** [comment]
I solve this problem by change the 81 to 80 ,  I feel it is successful ,because it give me this message:
```
{'rois': array([], shape=(0, 4), dtype=int32), 'class': array([], dtype=int32), 'scores': array([], dtype=float32), 'mask': array([], shape=(1440, 1080, 0), dtype=float64)}]
```
 I want to ask you a  queston, can you explain to me why it print the 'rois','class','scores','mask'?　 and why the four value  is None.  it just print eh shape and the dtype?

**Comment by buaacarzp** [comment]
can you help me .... why my print have  not  values,only a shape size inside.



18811746117@163.com
 
From: Bendang
Date: 2019-06-12 16:01
To: bendangnuksung/mrcnn_serving_ready
CC: buaacarzp; Mention
Subject: Re: [bendangnuksung/mrcnn_serving_ready] In the coco model, when I use resnet100 and resnet50 to generate h5 files to pb files respectively, why can both be generated ok? (#8)
Serving model can be used by tensorflow_model_server to deploy models on production.
forward_model expects a list of images. i.e it requires input shape of (N_Images, height, width, channel)
here is the code I use to call the forward_model
from forward import ForwardModel
import cv2
import numpy as np
frozen_graph_path = "frozen_model/mask_frozen_graph.pb"
# assign your own Config class
from config import mask_config
my_config = mask_config(5)
forward_model = ForwardModel(frozen_graph_path, my_config)
def test_one_image(image):
    images = np.expand_dims(image, axis=0)
    results = forward_model(images)
    return results
if __name__ == "__main__":
    test_image_path = 'XYZ.jpg'
    image = cv2.imread(test_image_path)
    r = test_one_image(image)
    print(r)

**Comment by bendangnuksung** [comment]
Sorry for the late reply. Looks like you have used `my_config = mask_config(5)`, you have to use your own config which you have used above.  `my_config = get_config1()`

**Comment by buaacarzp** [comment]
> Sorry for the late reply. Looks like you have used my_config = mask_config(5), you have to use your own config which you have used above.  my_config = get_config1()

dear bendangnuksung , I understand your meaning of that, but I use the coco model from , it contains 81 classes in that trained model, so I am true that I set the my_config = mask_config(80) , and I use a image from``` https://github.com/matterport/Mask_RCNN/tree/master/images ```  to inference the pb model is right, but here is no output,and it print the  ``` {'rois': array([], shape=(0, 4), dtype=int32), 'class': array([], dtype=int32), 'scores': array([], dtype=float32), 'mask': array([], shape=(1440, 1080, 0), dtype=float64)}]```, without the information of the mask and  the class, so I am confused  of it .
my config like the``` https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py```,  the model I download is the ```maksrcnn_coco.h5```, how can I overcome this problem? please help me . this problem I have tryed many times , but it didn't work.

**Comment by buaacarzp** [comment]
> Sorry for the late reply. Looks like you have used my_config = mask_config(5), you have to use your own config which you have used above.  my_config = get_config1()

Can you send me your model file ?  thank you very much

**Comment by buaacarzp** [comment]
> Sorry for the late reply. Looks like you have used `my_config = mask_config(5)`, you have to use your own config which you have used above. `my_config = get_config1()`

I got it, thank you very much , thanks, now  it print the 
```
[{'rois': array([[ 94, 141, 380, 590],
       [261,   0, 341,  91],
       [260, 536, 365, 629],
       [282, 611, 351, 640],
       [256,  72, 286,  96],
       [247,  89, 313, 145],
       [278, 599, 299, 610],
       [262,   4, 289,  80]], dtype=int32), 'class': array([6, 3, 3, 3, 3, 3, 1, 3], dtype=int32), 'scores': array([0.9999424 , 0.9876124 , 0.98480034, 0.9665876 , 0.96335596,
       0.94175243, 0.74342126, 0.7117303 ], dtype=float32), 'mask': array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],

```
 Next, I want to ask you  how to generate a pbtxt file ,because I want to use the opencv ,DNN module to  load my model and inference , please help me .

**Comment by bendangnuksung** [comment]
Sorry but I don't know how to generate pbtxt file to be used in opencv. A user said it was was not  able to read by opencv  link: https://github.com/bendangnuksung/mrcnn_serving_ready/issues/7#issuecomment-491193911

**Comment by buaacarzp** [comment]
> Sorry but I don't know how to generate pbtxt file to be used in opencv. A user said it was was not able to read by opencv link: [#7 (comment)](https://github.com/bendangnuksung/mrcnn_serving_ready/issues/7#issuecomment-491193911)

I can’t understand your answer...  why there many people want to generate the pb file but they didn’t load the pbtxt file to use the opencv dnn module? I don’t understand it...

**Comment by angyee** [comment]
> > Sorry for the late reply. Looks like you have used `my_config = mask_config(5)`, you have to use your own config which you have used above. `my_config = get_config1()`
> 
> I got it, thank you very much , thanks, now it print the
> 
> ```
> [{'rois': array([[ 94, 141, 380, 590],
>        [261,   0, 341,  91],
>        [260, 536, 365, 629],
>        [282, 611, 351, 640],
>        [256,  72, 286,  96],
>        [247,  89, 313, 145],
>        [278, 599, 299, 610],
>        [262,   4, 289,  80]], dtype=int32), 'class': array([6, 3, 3, 3, 3, 3, 1, 3], dtype=int32), 'scores': array([0.9999424 , 0.9876124 , 0.98480034, 0.9665876 , 0.96335596,
>        0.94175243, 0.74342126, 0.7117303 ], dtype=float32), 'mask': array([[[False, False, False, ..., False, False, False],
>         [False, False, False, ..., False, False, False],
>         [False, False, False, ..., False, False, False],
>         ...,
>         [False, False, False, ..., False, False, False],
>         [False, False, False, ..., False, False, False],
>         [False, False, False, ..., False, False, False]],
> 
>        [[False, False, False, ..., False, False, False],
> ```
> 
> Next, I want to ask you how to generate a pbtxt file ,because I want to use the opencv ,DNN module to load my model and inference , please help me .

how to show the result masked image ?
@buaacarzp @bendangnuksung

**Comment by bendangnuksung** [comment]
Closing as the original issue has been solved.
