### ISSUE TITLE
how to Use the frozen Model

### ISSUE THREAD

**Issue by angyee** [bendangnuksung/mrcnn_serving_ready#9]
I have the mask_frozen_graph.pb, now how to run on command line and use it?

@bendangnuksung @bendangnuksung

**Comment by bendangnuksung** [comment]
You can download the [forward.zip](https://github.com/matterport/Mask_RCNN/issues/218#issuecomment-476106031) provided in the comment and use the code below to inference it.

```python
from forward import ForwardModel
import cv2
import numpy as np

frozen_graph_path = "frozen_model/mask_frozen_graph.pb"

# assign your own Config class
my_config = YOUR_CONFIG_CLASS

forward_model = ForwardModel(frozen_graph_path, my_config)

def test_one_image(image):
    images = np.expand_dims(image, axis=0)
    results = forward_model(images)
    return results

if __name__ == "__main__":
    test_image_path = 'XYZ.jpg'
    image = cv2.imread(test_image_path)
    r = test_one_image(image)
    print(r)
```

**Comment by angyee** [comment]
> You can download the [forward.zip](https://github.com/matterport/Mask_RCNN/issues/218#issuecomment-476106031) provided in the comment and use the code below to inference it.
> 
> ```python
> from forward import ForwardModel
> import cv2
> import numpy as np
> 
> frozen_graph_path = "frozen_model/mask_frozen_graph.pb"
> 
> # assign your own Config class
> my_config = YOUR_CONFIG_CLASS
> 
> forward_model = ForwardModel(frozen_graph_path, my_config)
> 
> def test_one_image(image):
>     images = np.expand_dims(image, axis=0)
>     results = forward_model(images)
>     return results
> 
> if __name__ == "__main__":
>     test_image_path = 'XYZ.jpg'
>     image = cv2.imread(test_image_path)
>     r = test_one_image(image)
>     print(r)
> ```

what is my_config? how to set that? I have your files which converts keras to tensorflow means .h5 to .pb. so how to run on command line? i have edited with path of .pb and image now my_config not defined, how to do that?

**Comment by bendangnuksung** [comment]
`my_config` is a class which contains all the hyper-parameters of the model. You can find config class in [Mask_RCNN](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py) called `class Config(object)`. In the same manner, you might have used your own config class to train the model. Assign that config class to `my_config`

**Comment by angyee** [comment]
> `my_config` is a class which contains all the hyper-parameters of the model. You can find config class in [Mask_RCNN](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py) called `class Config(object)`. In the same manner, you might have used your own config class to train the model. Assign that config class to `my_config`

from forward import ForwardModel
import cv2
import numpy as np

frozen_graph_path = "/home/deepedge/mask_rcnn-master/mask_dent_frozen_graph.pb"

# assign your own Config class
my_config = "/home/deepedge/mask_rcnn-master/mrcnn/config.py" 

forward_model = ForwardModel(frozen_graph_path, my_config)

def test_one_image(image):
    images = np.expand_dims(image, axis=0)
    results = forward_model(images)
    return results

if __name__ == "__main__":
    test_image_path = '/home/deepedge/mask_rcnn-master/mask-rcnn-bottle-training-master/dataset/val/car39.jpg'
    image = cv2.imread(test_image_path)
    r = test_one_image(image)
    print(r)


error 

$ python3 anomaly.py 

2019-07-01 11:02:29.101152: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-01 11:02:29.120748: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-07-01 11:02:29.121268: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0xe58be0 executing computations on platform Host. Devices:
2019-07-01 11:02:29.121280: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "anomaly.py", line 20, in <module>
    r = test_one_image(image)
  File "anomaly.py", line 14, in test_one_image
    results = forward_model(images)
  File "/home/deepedge/mask_rcnn-master/mrcnn_serving_ready-master/forward.py", line 218, in __call__
    molded_images, image_metas, windows = self.mold_inputs(images)
  File "/home/deepedge/mask_rcnn-master/mrcnn_serving_ready-master/forward.py", line 93, in mold_inputs
    min_dim=self.config.IMAGE_MIN_DIM,
AttributeError: 'str' object has no attribute 'IMAGE_MIN_DIM'

@bendangnuksung

**Comment by angyee** [comment]
> `my_config` is a class which contains all the hyper-parameters of the model. You can find config class in [Mask_RCNN](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py) called `class Config(object)`. In the same manner, you might have used your own config class to train the model. Assign that config class to `my_config`

like this
my_config = "/home/deepedge/mask_rcnn-master/mrcnn/config.py"

**Comment by ibrahimLearning** [comment]
@bendangnuksung 
Thanks for your code. I used your successfully for detection using frozen model (.pb). 
How can I save your serving ready model in .pb.? I would like to use it opencv dnn

**Comment by i-chaochen** [comment]
> `my_config` is a class which contains all the hyper-parameters of the model. You can find config class in [Mask_RCNN](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py) called `class Config(object)`. In the same manner, you might have used your own config class to train the model. Assign that config class to `my_config`

I got the different results when I used the frozen graph, is it normal?
https://github.com/matterport/Mask_RCNN/issues/1668

**Comment by YUHAO19910716** [comment]
@angyee 

from forward import ForwardModel
import cv2
import numpy as np



class mask_config():
    def __init__(self, NUMBER_OF_CLASSES):
        self.NAME = "tags"
        self.IMAGES_PER_GPU = 1
        self.NUM_CLASSES = 1 + NUMBER_OF_CLASSES  # Background + tags
        self.STEPS_PER_EPOCH = 100
        self.DETECTION_MIN_CONFIDENCE = 0.9
        self.GPU_COUNT = 1
        self.IMAGES_PER_GPU = 1
        self.NAME = None  # Override in sub-classes
        self.GPU_COUNT = 1
        self.IMAGES_PER_GPU = 1
        self.STEPS_PER_EPOCH = 1000
        self.VALIDATION_STEPS = 50
        self.BACKBONE = "resnet101"
        self.COMPUTE_BACKBONE_SHAPE = None
        self.BACKBONE_STRIDES = [4, 8, 16, 32, 64]
        self.FPN_CLASSIF_FC_LAYERS_SIZE = 1024
        self.TOP_DOWN_PYRAMID_SIZE = 256
        self.RPN_ANCHOR_SCALES = (32, 64, 128, 256, 512)
        self.RPN_ANCHOR_RATIOS = [0.5, 1, 2]
        self.RPN_ANCHOR_STRIDE = 1
        self.RPN_NMS_THRESHOLD = 0.7
        self.RPN_TRAIN_ANCHORS_PER_IMAGE = 256
        self.POST_NMS_ROIS_TRAINING = 2000
        self.POST_NMS_ROIS_INFERENCE = 1000
        self.USE_MINI_MASK = True
        self.MINI_MASK_SHAPE = (56, 56)  # (height, width) of the mini-mask
        self.IMAGE_RESIZE_MODE = "square"
        self.IMAGE_MIN_DIM = 800
        self.IMAGE_MAX_DIM = 1024
        self.IMAGE_MIN_SCALE = 0
        self.MEAN_PIXEL = np.array([123.7, 116.8, 103.9])
        self.TRAIN_ROIS_PER_IMAGE = 200
        self.ROI_POSITIVE_RATIO = 0.33
        self.POOL_SIZE = 7
        self.MASK_POOL_SIZE = 14
        self.MASK_SHAPE = [28, 28]
        self.MAX_GT_INSTANCES = 100
        self.RPN_BBOX_STD_DEV = np.array([0.1, 0.1, 0.2, 0.2])
        self.BBOX_STD_DEV = np.array([0.1, 0.1, 0.2, 0.2])
        self.DETECTION_MAX_INSTANCES = 100
        self.DETECTION_MIN_CONFIDENCE = 0.7
        self.DETECTION_NMS_THRESHOLD = 0.3
        self.LEARNING_RATE = 0.001
        self.LEARNING_MOMENTUM = 0.9
        self.WEIGHT_DECAY = 0.0001
        self.LOSS_WEIGHTS = {"rpn_class_loss": 1., "rpn_bbox_loss": 1., "mrcnn_class_loss": 1., "mrcnn_bbox_loss": 1.,
                             "mrcnn_mask_loss": 1.}
        self.USE_RPN_ROIS = True
        self.TRAIN_BN = False  # Defaulting to False since batch size is often small
        self.GRADIENT_CLIP_NORM = 5.0

        self.BATCH_SIZE = self.IMAGES_PER_GPU * self.GPU_COUNT

        # Input image size
        if self.IMAGE_RESIZE_MODE == "crop":
            self.IMAGE_SHAPE = np.array([self.IMAGE_MIN_DIM, self.IMAGE_MIN_DIM, 3])
        else:
            self.IMAGE_SHAPE = np.array([self.IMAGE_MAX_DIM, self.IMAGE_MAX_DIM, 3])

        # Image meta data length
        # See compose_image_meta() for details
        self.IMAGE_META_SIZE = 1 + 3 + 3 + 4 + 1 + self.NUM_CLASSES

# assign your own Config class
my_config = mask_config(3)


frozen_graph_path = "./mask_frozen_graph.pb"
# frozen_graph_path = "./saved_model.pb"


forward_model = ForwardModel(frozen_graph_path, my_config)
print(111)

def test_one_image(image):
    images = np.expand_dims(image, axis=0)
    results = forward_model(images)
    return results

import visualize
if __name__ == "__main__":
    test_image_path = 'yuhao_square.png'
    image = cv2.imread(test_image_path)
    image = cv2.resize(image, (128, 128), interpolation=cv2.INTER_CUBIC)
    print(image)
    print(np.shape(image))
    results = test_one_image(image)
    print(results)
    class_names=['BG', 'square', 'circle', 'triangle']
    r = results[0]
    visualize.display_instances(image, r['rois'], r['mask'], r['class'],
                                class_names, r['scores'])


this code can run,

**Comment by ibrahimLearning** [comment]
@YUHAO19910716 
Thanks for your comment. Would you give a suggestion please?
How can I use the .pb model in opencv dnn? I created .pb and also tested successfully using the similar code which you provided here. Unfortunately, I can not use it in opencv dnn.

Thanks
Khalilullah
